"""is editing

Revision ID: c051007a1024
Revises: 7046c1aa518d
Create Date: 2018-07-17 18:19:06.552855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c051007a1024'
down_revision = '7046c1aa518d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_editing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_editing')
    # ### end Alembic commands ###
